config/routes.rb
Rails.application.routes.draw do
  get 'api', to: 'api#search', as:"search"
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

 protect_from_forgery except: :search

  def search

  	@recipes = api_call(1).concat(api_call(2))

  	render "api/search.js.erb"
  end

  private 

  def api_call(page)
  	param = params["q"]
  	recipes_call = HTTParty.get('http://www.recipepuppy.com/api/?q='+ param + '&p=' + page.to_s)
	recipes_json = JSON.parse(CGI::unescapeHTML(recipes_call.body))

	recipes_json["results"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Recipe finder</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Home", root_path, :class => "nav-link" %>
          </li>      
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">

	<%= form_tag search_path , remote: true, method: :get, id: 'recipe-search' do %>
		
		<div class="form-row margin-default-space">
			<%= text_field_tag :q, params[:q], placeholder: 'Recipe name', autofocus: true, :class => "form-control col-md-10" %>
		
			<%= submit_tag "Search", :class => "btn col-md-2" %>
		</div>
		
	<% end %>	 




<table class="table table-striped margin-default-space">
  <tbody id="result-list">

  </tbody>
</table>


		
</div>